development: &default
  adapter: postgresql
  database: blog_development
  encoding: utf8
  min_messages: warning
  username: ian
  password: supersecret
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: blog_test
